color: violet
fieldLayouts:
  7f3a0072-9bae-4175-bed4-090cbae024b4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 26ccb539-4155-4075-bacd-0665d644bdc1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aceb685c-e2ab-4797-b484-deef314f6c47 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6f70ad5-9581-492e-8ac9-755bd34c8ac4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 88133f30-bcf3-46dd-b19d-5e8efdf65266
        userCondition: null
handle: about
hasTitleField: true
icon: address-card
name: about
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
