color: amber
fieldLayouts:
  78f60e4f-6828-4ed1-846f-5580c85cf2c9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a2760bd6-cd03-47e5-b0a9-40d59441aab0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aceb685c-e2ab-4797-b484-deef314f6c47 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c18d3e4-9c3a-47f7-8390-2ad2038d8489
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bea20149-7ca0-4687-b559-9cef0efac9de
        userCondition: null
handle: aboutUs
hasTitleField: true
icon: address-card
name: 'about us'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
