color: indigo
fieldLayouts:
  3e0e0214-d260-4cd1-9254-a007eacfff74:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 53f7f122-72e3-4a62-ae42-b14d6ccc0d27
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aceb685c-e2ab-4797-b484-deef314f6c47 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25c98b68-2a43-4e3b-aaac-cff4576c734e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbc74a67-01ff-43f5-aff7-130a4a88b827 # Portfolio Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2bc6a1c-a05a-45eb-9047-8f9c9644768d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2032a165-58d4-47e3-ba24-5fd93be613da
        userCondition: null
handle: featuredProjects
hasTitleField: true
icon: cannon
name: 'featured projects'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
