color: orange
fieldLayouts:
  6dd64e26-e970-4e57-9b02-e62af76e57d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b4446cac-bd2a-4d81-8ab2-608de7244f13
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b001ba68-b3f9-4f1e-8d90-79f570ab6c3c # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 631c88c7-fd09-4d3f-8084-61c6897b8b43
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c0d38d04-1dae-4f65-ab4e-3569841f48c6 # Hero Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20c276fb-d37a-4021-b0f0-b6c5af2d5653
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ce74db51-2699-4917-8734-9769c5df7ceb # Hero Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8340550c-a13b-4271-8b7a-0e19fce00030
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aceb685c-e2ab-4797-b484-deef314f6c47 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8835cdbb-348d-4ec6-a253-0c3531f1b596
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 95dc20da-182e-4ef4-93ec-c846a6a919c7
        userCondition: null
handle: home
hasTitleField: true
icon: house
name: home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
