color: red
fieldLayouts:
  fc0b2c30-fa11-4bc1-b522-e0bc960fdd41:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b001ba68-b3f9-4f1e-8d90-79f570ab6c3c # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6d3a85a-a3e0-4a27-8e2f-8886b6dc5d20
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 82a4ca89-5cca-4e6a-9c67-bc0f3e224c36
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aceb685c-e2ab-4797-b484-deef314f6c47 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16c5379b-fe22-4493-aeed-b6cab1d818d1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 70b42984-e6d5-40ef-a6f0-e7d3c14aad3a
        userCondition: null
handle: home
hasTitleField: true
icon: house
name: home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
