color: rose
fieldLayouts:
  790ee856-37a6-455e-b749-d3cc6ba07ff1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c8878e87-4eae-4778-8ae8-6a842a2c507d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b001ba68-b3f9-4f1e-8d90-79f570ab6c3c # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c2d71cc-1887-404b-9e6a-e746accc2cc9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8ebf2c79-92fc-4e47-a879-5c95c4538a34
        userCondition: null
handle: portfolioHome
hasTitleField: true
icon: house
name: 'portfolio home'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
