baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'The Company of Landscapers'
primary: true
siteGroup: 4a535fdc-5034-43ae-bbff-b5d1b8b0ec27 # company-of-landscapers
sortOrder: 1
