altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  b5e066aa-67d2-4730-a5f0-d0611f0c5ccd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f198cdd1-fee2-41b2-a171-e4a5262b19e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aceb685c-e2ab-4797-b484-deef314f6c47 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3967682-c5b9-4f96-abc8-5adf420311f5
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 1e6cbd7b-0eba-4334-ad0b-a9289d31002d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 19b38792-e195-4b34-a2b8-c703e40393f8
        userCondition: null
fs: hardDisk
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
