isPublic: false
name: 'Company of Landscapers'
scope:
  - 'sites.102e3dff-3159-462b-a2ee-18957798f6d7:read' # company-of-landscapers
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.a020d92f-e1bd-41f9-ab8e-28581deb0902:read' # Home
  - 'sections.4bc0b01b-ec98-4d67-9258-7ac792b89ea5:read' # Portfolio Home
  - 'sections.a7b1de76-4c29-4448-b3f9-ee346e9c8ecd:read' # Portfolio
  - 'volumes.a64bad47-8bd1-4e6b-941a-c69229d717cb:read' # Images
  - 'globalsets.e85ddff0-4029-4929-a287-92eaf0c83603:read' # Contact Information
  - 'categorygroups.f26d5401-bbcb-4d6d-9285-01a9e394ebae:read' # Types
  - 'sections.a020d92f-e1bd-41f9-ab8e-28581deb0902:save' # Home
  - 'sections.a7b1de76-4c29-4448-b3f9-ee346e9c8ecd:edit' # Portfolio
  - 'sections.a7b1de76-4c29-4448-b3f9-ee346e9c8ecd:create' # Portfolio
  - 'sections.a7b1de76-4c29-4448-b3f9-ee346e9c8ecd:save' # Portfolio
  - 'sections.a7b1de76-4c29-4448-b3f9-ee346e9c8ecd:delete' # Portfolio
  - 'volumes.a64bad47-8bd1-4e6b-941a-c69229d717cb:edit' # Images
  - 'volumes.a64bad47-8bd1-4e6b-941a-c69229d717cb:create' # Images
  - 'volumes.a64bad47-8bd1-4e6b-941a-c69229d717cb:save' # Images
  - 'volumes.a64bad47-8bd1-4e6b-941a-c69229d717cb:delete' # Images
  - 'globalsets.e85ddff0-4029-4929-a287-92eaf0c83603:edit' # Contact Information
  - 'categorygroups.f26d5401-bbcb-4d6d-9285-01a9e394ebae:edit' # Types
  - 'categorygroups.f26d5401-bbcb-4d6d-9285-01a9e394ebae:save' # Types
  - 'categorygroups.f26d5401-bbcb-4d6d-9285-01a9e394ebae:delete' # Types
