columnSuffix: null
handle: featuredProjects
instructions: null
name: 'Featured Projects'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 4ff36937-2014-455b-98f6-2f4e01565bac # featured projects
  includeTableView: false
  maxEntries: 4
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
