columnSuffix: null
handle: streetAddress
instructions: null
name: 'Street Address'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: 'Address here...'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
