dateModified: 1717436863
email:
  fromEmail: agdc101@gmail.com
  fromName: company-of-landscapers
  transportType: craft\mail\transportadapters\Sendmail
fs:
  hardDisk:
    hasUrls: true
    name: 'Hard Disk'
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
meta:
  __names__:
    4a535fdc-5034-43ae-bbff-b5d1b8b0ec27: company-of-landscapers # company-of-landscapers
    8f75fe13-3a1f-44e6-a18d-1130662e3782: 'Portfolio Types' # Portfolio Types
    52f8665f-4695-4e8b-a474-e305afee4de0: 'about us' # about us
    102e3dff-3159-462b-a2ee-18957798f6d7: company-of-landscapers # company-of-landscapers
    a7b1de76-4c29-4448-b3f9-ee346e9c8ecd: Portfolio # Portfolio
    a64bad47-8bd1-4e6b-941a-c69229d717cb: Images # Images
    aceb685c-e2ab-4797-b484-deef314f6c47: Description # Description
    bf50b81f-54e8-4247-bbf6-61ecef6a8462: portfolio # portfolio
    ca6860b8-46dc-4946-816c-8951d3c6e415: 'Public Schema' # Public Schema
    d1babea9-964e-43b8-a8df-1396d57e83ae: 'About us' # About us
    dbc74a67-01ff-43f5-aff7-130a4a88b827: 'Portfolio Image' # Portfolio Image
    f26d5401-bbcb-4d6d-9285-01a9e394ebae: Types # Types
plugins:
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: company-of-landscapers
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
