dateModified: 1715931833
email:
  fromEmail: agdc101@gmail.com
  fromName: company-of-landscapers
  transportType: craft\mail\transportadapters\Sendmail
fs:
  hardDisk:
    hasUrls: false
    name: 'Hard Disk'
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: null
meta:
  __names__:
    4a535fdc-5034-43ae-bbff-b5d1b8b0ec27: company-of-landscapers # company-of-landscapers
    8f75fe13-3a1f-44e6-a18d-1130662e3782: 'Portfolio Types' # Portfolio Types
    68b0f868-fbd5-4266-b5a6-e3a855057f54: Cunt # Cunt
    102e3dff-3159-462b-a2ee-18957798f6d7: company-of-landscapers # company-of-landscapers
    a7b1de76-4c29-4448-b3f9-ee346e9c8ecd: Portfolio # Portfolio
    a64bad47-8bd1-4e6b-941a-c69229d717cb: Images # Images
    aceb685c-e2ab-4797-b484-deef314f6c47: Description # Description
    bf50b81f-54e8-4247-bbf6-61ecef6a8462: 'Portfolio 1' # Portfolio 1
    ca6860b8-46dc-4946-816c-8951d3c6e415: 'Public Schema' # Public Schema
    dbc74a67-01ff-43f5-aff7-130a4a88b827: 'Feature Image' # Feature Image
    f26d5401-bbcb-4d6d-9285-01a9e394ebae: Types # Types
system:
  edition: solo
  live: true
  name: company-of-landscapers
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
