dateModified: 1725201919
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      key: singles
      type: native
    -
      heading: Channels
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:a7b1de76-4c29-4448-b3f9-ee346e9c8ecd' # Portfolio
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
        - 'field:8f75fe13-3a1f-44e6-a18d-1130662e3782' # Portfolio Types
      type: native
email:
  fromEmail: agdc101@gmail.com
  fromName: company-of-landscapers
  transportType: craft\mail\transportadapters\Sendmail
fs:
  googleCloudStorage:
    hasUrls: true
    name: 'Google Cloud Storage'
    settings:
      bucket: craft-gcs-storage
      bucketSelectionMode: choose
      expires: ''
      keyFileContents: $GCS_KEY_FILE
      projectId: $GCS_PROJECT_ID
      subfolder: ''
      visibility: null
    type: craft\googlecloud\Fs
    url: 'http://storage.googleapis.com/craft-gcs-storage/'
  hardDisk:
    hasUrls: true
    name: 'Hard Disk'
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
meta:
  __names__:
    4a535fdc-5034-43ae-bbff-b5d1b8b0ec27: company-of-landscapers # company-of-landscapers
    4bc0b01b-ec98-4d67-9258-7ac792b89ea5: 'Portfolio Home' # Portfolio Home
    4c4d247d-fc4e-46ea-8524-f022a87811f6: Contact # Contact
    5ba59a8e-8f7d-4263-8953-9ecb6b08e60d: about # about
    6d6d30ea-3be2-411e-ae32-b53bce8c7ff5: 'Phone Number' # Phone Number
    7cd5775b-a151-47cc-8ae5-9c3c603098b9: 'Google Storage' # Google Storage
    8f75fe13-3a1f-44e6-a18d-1130662e3782: 'Portfolio Types' # Portfolio Types
    9cbc0be7-2e25-41b0-8cbe-798aa8e3a380: 'Experience Description' # Experience Description
    45d83c52-358c-4eb0-a0bf-a98df87151bd: 'Intro Description' # Intro Description
    102e3dff-3159-462b-a2ee-18957798f6d7: company-of-landscapers # company-of-landscapers
    1501e96a-99b5-4803-8e1b-35d30f7ef800: 'Social Link' # Social Link
    4628a1f0-6346-446d-ae6b-0516f4466cbc: 'Experience Title' # Experience Title
    4979a5b7-ce59-477e-92d9-70531382c552: Address # Address
    5212e7c6-8d20-4c54-9720-1d3464693fb8: 'Street Address' # Street Address
    65032f45-2139-461d-a905-0e01e328d598: 'Intro Image' # Intro Image
    915857dd-f635-4a43-ac1d-b56aade82396: 'Intro Title' # Intro Title
    05088608-0a21-44e0-9cc9-4868e395af3d: contact # contact
    94829161-2dd5-4e9b-afd5-bd800f248757: home # home
    a020d92f-e1bd-41f9-ab8e-28581deb0902: Home # Home
    a7b1de76-4c29-4448-b3f9-ee346e9c8ecd: Portfolio # Portfolio
    a64bad47-8bd1-4e6b-941a-c69229d717cb: Images # Images
    aceb685c-e2ab-4797-b484-deef314f6c47: Description # Description
    ae5cb1b6-ff87-4394-be39-61c36b97dac5: 'Company of Landscapers' # Company of Landscapers
    b001ba68-b3f9-4f1e-8d90-79f570ab6c3c: 'Hero Image' # Hero Image
    bd9865ce-0612-429f-9fdd-e6272c09da53: category # category
    bef872f0-be53-4c18-a75b-17c7ab9ea4b4: Email # Email
    bf50b81f-54e8-4247-bbf6-61ecef6a8462: portfolio # portfolio
    c0d38d04-1dae-4f65-ab4e-3569841f48c6: 'Hero Title' # Hero Title
    ca6860b8-46dc-4946-816c-8951d3c6e415: 'Public Schema' # Public Schema
    ce74db51-2699-4917-8734-9769c5df7ceb: 'Hero Text' # Hero Text
    d6fae4f2-b9a8-4131-b09d-4e457c4d77fc: 'Experience Image' # Experience Image
    dbc74a67-01ff-43f5-aff7-130a4a88b827: 'Portfolio Images' # Portfolio Images
    e85ddff0-4029-4929-a287-92eaf0c83603: 'Contact Information' # Contact Information
    ef7b4039-ac13-4438-be1e-6e99da5a5441: 'Project Description' # Project Description
    f26d5401-bbcb-4d6d-9285-01a9e394ebae: Types # Types
    f3577129-b42e-4ebb-bc16-a26371c1cf84: 'portfolio home' # portfolio home
plugins:
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  google-cloud:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
system:
  edition: solo
  live: true
  name: company-of-landscapers
  schemaVersion: 5.0.0.21
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
