defaultPlacement: end
enableVersioning: true
entryTypes:
  - 52f8665f-4695-4e8b-a474-e305afee4de0 # about us
handle: aboutUs
maxAuthors: 1
name: 'About us'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  102e3dff-3159-462b-a2ee-18957798f6d7: # company-of-landscapers
    enabledByDefault: true
    hasUrls: true
    template: about-us/_entry
    uriFormat: about-us
type: single
