defaultPlacement: end
enableVersioning: true
entryTypes:
  - 94829161-2dd5-4e9b-afd5-bd800f248757 # home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  102e3dff-3159-462b-a2ee-18957798f6d7: # The Company of Landscapers
    enabledByDefault: true
    hasUrls: true
    template: home/_entry
    uriFormat: __home__
type: single
