defaultPlacement: end
enableVersioning: true
entryTypes:
  - 9d9dcee3-fe9b-41a3-869e-02fb357a8bd1 # home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  102e3dff-3159-462b-a2ee-18957798f6d7: # company-of-landscapers
    enabledByDefault: true
    hasUrls: true
    template: home/_entry
    uriFormat: __home__
type: single
